### ISSUE TITLE
ci: Update to Flutter 3.16.0/Dart 3.2

### ISSUE THREAD

**Issue by tomarra** [VeryGoodOpenSource/very_good_flutter_package#71]
**Description**

Update to the latest version given new releases

**Requirements**

- [ ] The ci system is passing

**Comment by alestiago** [comment]
We're moving this repository to [Very Good Templates](https://github.com/VeryGoodOpenSource/very_good_templates). Hence, I'm closing this issue in favour of https://github.com/VeryGoodOpenSource/very_good_templates/issues/17.
